# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USE=postgres"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=dl_growth_solutions"
    ports:
      - 5441:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  pg-dada: